"""initial schema

Revision ID: 737135f24457
Revises: 
Create Date: 2026-08-27 14:34:19.581075

"""
from __future__ import annotations

from alembic import op
import sqlalchemy as sa


revision = '737135f24457'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('handle', sa.Text(), nullable=False),
    sa.Column('email', sa.Text(), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('role', sa.Text(), nullable=False),
    sa.Column('locale', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('handle')
    )
    op.create_table('site_comments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('deleted_at', sa.Text(), nullable=True),
    sa.Column('deleted_by', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['deleted_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('site_comments', schema=None) as batch_op:
        batch_op.create_index('ix_site_comments_site_created', ['site_id', 'created_at'], unique=False)

    op.create_table('site_confirmations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('confirmed_on', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('site_id', 'user_id', name='uq_confirmation_site_user')
    )
    with op.batch_alter_table('site_confirmations', schema=None) as batch_op:
        batch_op.create_index('ix_confirmations_site_date', ['site_id', 'confirmed_on'], unique=False)

    op.create_table('site_reports',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('site_id', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category', sa.Text(), nullable=False),
    sa.Column('body', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('resolved_by', sa.Integer(), nullable=True),
    sa.Column('resolved_at', sa.Text(), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['resolved_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('site_reports', schema=None) as batch_op:
        batch_op.create_index('ix_site_reports_site', ['site_id'], unique=False)
        batch_op.create_index('ix_site_reports_status_created', ['status', 'created_at'], unique=False)

    op.create_table('terms_acceptances',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('terms_version', sa.Text(), nullable=False),
    sa.Column('accepted_at', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('submissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.Text(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.Text(), nullable=False),
    sa.Column('target_site_id', sa.Text(), nullable=True),
    sa.Column('payload_json', sa.Text(), nullable=False),
    sa.Column('moderator_payload_json', sa.Text(), nullable=True),
    sa.Column('normalized_json', sa.Text(), nullable=True),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('machine_flags_json', sa.Text(), nullable=False),
    sa.Column('terms_acceptance_id', sa.Integer(), nullable=False),
    sa.Column('decided_by', sa.Integer(), nullable=True),
    sa.Column('decided_at', sa.Text(), nullable=True),
    sa.Column('published_commit_sha', sa.Text(), nullable=True),
    sa.Column('published_site_id', sa.Text(), nullable=True),
    sa.Column('published_at', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['decided_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['terms_acceptance_id'], ['terms_acceptances.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('public_id')
    )
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.create_index('ix_submissions_status_created', ['status', 'created_at'], unique=False)
        batch_op.create_index('ix_submissions_user', ['user_id'], unique=False)

    op.create_table('media_uploads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sha256', sa.Text(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('uploader_user_id', sa.Integer(), nullable=False),
    sa.Column('original_filename', sa.Text(), nullable=True),
    sa.Column('mime_type', sa.Text(), nullable=False),
    sa.Column('size_bytes', sa.Integer(), nullable=False),
    sa.Column('width', sa.Integer(), nullable=True),
    sa.Column('height', sa.Integer(), nullable=True),
    sa.Column('caption', sa.Text(), nullable=True),
    sa.Column('licence', sa.Text(), nullable=False),
    sa.Column('storage_path', sa.Text(), nullable=False),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.ForeignKeyConstraint(['uploader_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('sha256')
    )
    op.create_table('submission_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('event', sa.Text(), nullable=False),
    sa.Column('from_status', sa.Text(), nullable=True),
    sa.Column('to_status', sa.Text(), nullable=True),
    sa.Column('detail_json', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('submission_messages',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('submission_id', sa.Integer(), nullable=False),
    sa.Column('author_user_id', sa.Integer(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('visibility', sa.Text(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['submission_id'], ['submissions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('submission_messages')
    op.drop_table('submission_events')
    op.drop_table('media_uploads')
    with op.batch_alter_table('submissions', schema=None) as batch_op:
        batch_op.drop_index('ix_submissions_user')
        batch_op.drop_index('ix_submissions_status_created')

    op.drop_table('submissions')
    op.drop_table('terms_acceptances')
    with op.batch_alter_table('site_reports', schema=None) as batch_op:
        batch_op.drop_index('ix_site_reports_status_created')
        batch_op.drop_index('ix_site_reports_site')

    op.drop_table('site_reports')
    with op.batch_alter_table('site_confirmations', schema=None) as batch_op:
        batch_op.drop_index('ix_confirmations_site_date')

    op.drop_table('site_confirmations')
    with op.batch_alter_table('site_comments', schema=None) as batch_op:
        batch_op.drop_index('ix_site_comments_site_created')

    op.drop_table('site_comments')
    op.drop_table('users')
    # ### end Alembic commands ###
